### ISSUE TITLE
No SQLiteDBAdapter available

### ISSUE THREAD

**Issue by kiesel** [xp-framework/rdbms#23]
In commit 1101dcae750495274467313d94b187573a649167, all of the *sqlite* package was removed in favor of the *sqlite3* package. That package, however, does not have an SQLiteDBAdapter, so we cannot do reflection on these kinds of databases any more.

Furthermore, we're now having an unresolved dependency in [`xp.codegen.dataset.Generator`](https://github.com/xp-framework/codegen/blob/master/src/main/php/xp/codegen/dataset/Generator.class.php#L57).

I suggest to extract the removed class from the referenced commit and add it to the *sqlite3* package.

**Comment by thekid** [comment]
Class reintroduced as `rdbms.sqlite3.SQLite3DBAdapter` in [7.2.2](https://github.com/xp-framework/rdbms/releases/tag/v7.2.2)
